# this is a C-PAC Docs content file 

paragraphs:
  - paragraph: The default processing pipeline performs fMRI processing using four strategies, with/without global signal regression, and with/without bandpass filtering.   C-PAC runs this pipeline by default, it is not necessary to invoke the –preconfig flag to run it.  

    subparagraphs:
      - paragraph: Anatomical Preprocessing
        details:
          - Anatomical processing begins with conforming the data to RPI orientation and removing orientation header information that will interfere with further processing.
          - A non-linear transform between skull-on images and a 2mm MNI brain-only template are calculated using ANTs.
          - Images are then skull-stripped using FSL’s BET and subsequently segmented into WM, GM, and CSF using FSL’s FAST tool.
          - The resulting WM mask is multiplied by a WM prior map that has been transformed into individual space using the inverse of the linear transforms previously calculated during the ANTs procedure.
          - A CSF mask is then multiplied by a ventricle map derived from the Harvard-Oxford atlas distributed with FSL.
          - Skull-stripped images and grey matter tissue maps are written into MNI space at 2mm resolution.  
      - paragraph: Functional Preprocessing
        details:
        - Functional preprocessing begins with resampling the data to RPI orientation and performing slice timing correction.
        - Next, motion correction is performed using a two-stage approach in which the images are first coregistered to the mean fMRI and then a new mean is calculated and used as the target for a second coregistration (AFNI 3dvolreg).
        - A 7 degree of freedom linear transform between the mean fMRI and the structural image is calculated using FSL’s implementation of boundary-based registration.
        - Nuisance variable regression (NVR) is performed on motion corrected data using a 2nd order polynomial, a 24-regressor model of motion[7], 5 nuisance signals, identified via principal components analysis of signals obtained from white matter (CompCor[8]), and mean CSF signal.
        - WM and CSF signals are extracted using the previously described masks after transforming the fMRI data to match them in 2mm space using the inverse of the linear fMRI-sMRI transform.
        - The NVR procedure is performed twice, with and without the inclusion of the global signal as a nuisance regressor.
        - The residuals of the NVR procedure are processed with and without bandpass filtering (0.01Hz < f < 0.1Hz), written into MNI space at 3mm resolution and subsequently smoothed using a 6mm FWHM kernel.
      - paragraph: Several different individual level analysis are performed on the fMRI data, including
        details:
        - Amplitude of low frequency fluctuations (alff)
        - Fractional amplitude of low frequency fluctuations (falff)
        - Regional homogeneity (ReHo)
        - Voxel mirrored homotopic connectivity (VMHC)
        - Weighted and binarized degree centrality (DC)
        - Eigenvector centrality (EC)
        - Local functional connectivity density (lFCD)
        - 10 intrinsic connectivity networks (ICNs) from dual regression
        - Seed correlation analysis (SCA)
        - Time series extraction

mermaid:
  title: null
  operations: null